### ISSUE TITLE
Storage overridden unexpectedly

### ISSUE THREAD

**Issue by kapsule-studio** [react18-tools/persist-and-sync#15]
Hi,

I have an issue where everything was working fine but then, I added a third property to `include` in the `sessionStorage`.
Instead of just adding it to the ones already there, anytime this third property is modified, the whole `sessionStorage` is cleared and only the third property is inside.

Here are my options (I don't show you the store's data because it is HUGE) 
![image](https://github.com/react18-tools/persist-and-sync/assets/77295465/f1d3a149-67a9-49fb-8568-e41439528636)

Here is my `sessionStorage` before a change occurs to `pagesConfig`. Notice that only `pages` and `history` are present.
![image](https://github.com/react18-tools/persist-and-sync/assets/77295465/aef58176-8489-4a2e-8f04-417522a75b25)

Here is a screenshot after I change `pagesConfig`, it just clears the `sessionStorage`. If now I update `pages` or `history` it will basically go back to the previous state with only both of them included in the `sessionStorage`.
![image](https://github.com/react18-tools/persist-and-sync/assets/77295465/60eb6709-b023-4bf4-9f3f-e2e4f1f2e627)

I'd simply like to store the 3 properties and at all time, with no override.

**Comment by mayank1513** [comment]
Please provide more details to reproduce the issue. Thanks.

**Comment by kapsule-studio** [comment]
Sorry, I posted the issue with only `Hi` in it because of a bad shortcut. You've been to quick to jump on it 😅

**Comment by kapsule-studio** [comment]
> Please provide more details to reproduce the issue. Thanks.

It would take me at least 1 hour to put up a minimal repo to reproduce the issue. I was expecting someone to have run into it and found a solution. For some context, I use that store with react's `useContext` to pass `props` to the store for initial values.

If I can't get any help, I'd rather spend time trying to find a workaround by myself than to create a mini repo that wouldn't necesseraly lead to a solution. Thanks anyway.

**Comment by kapsule-studio** [comment]
Alright. After some more digging, it ended up being quite simple. Whenever you use the `set()` method from Zustand, you have to set all the properties you keep in storage. Otherwise you'll just override it everytime with only the property that you changed.

For example:

```typescript
set({name: newName, age: get().age})
// or
set({age: newAge, name: get().name})
// if the other property is an object, you have to spread it into a new one
set({age: newAge, details: {...get().details}})
```

**Comment by kapsule-studio** [comment]
Alright. After some more digging, it ended up being quite simple. Whenever you use the `set()` method from Zustand, you have to set all the properties you keep in storage. Otherwise you'll just override it everytime with only the property that you changed.

For example:

```typescript
set({name: newName, age: get().age})
// or
set({age: newAge, name: get().name})
// if the other property is an object, you have to spread it into a new one
set({age: newAge, details: {...get().details}})
```
